base_url = "https://4mbjam.dev"

title = "4mbjam"

description = ""

default_language = "en"

compile_sass = true

generate_feeds = true

feed_filenames = ["rss.xml"]


taxonomies = [
    { name = "tags", paginate_by = 10, feed = true }
]

build_search_index = false

[markdown]

highlight_code = true


bottom_footnotes = false    

insert_anchor_links = "heading"


[extra]
liveReloadHostname = "test.moros1138.com"
